image: node:20-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/

stages:
  - validate
  - test
  - build
  - release
  - deploy

# ========================================
# ANCHORS
# ========================================

.rules-no-tag-no-release: &rules-no-tag-no-release
  rules:
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_MESSAGE !~ /^chore: release/'

.git-setup: &git-setup
  before_script:
    - apk add --no-cache git
    - git config user.email "${GITLAB_USER_EMAIL}"
    - git config user.name "${GITLAB_USER_NAME}"
    - git remote set-url origin "https://gitlab-ci-token:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git checkout "${CI_COMMIT_BRANCH}"
    - git pull origin "${CI_COMMIT_BRANCH}" --rebase

# ========================================
# JOBS
# ========================================

install:
  stage: .pre
  before_script:
    - apk add --no-cache git
  script:
    - npm ci --cache .npm --prefer-offline

lint:
  stage: validate
  script:
    - npm run lint
  <<: *rules-no-tag-no-release

test:
  stage: test
  script:
    - npm run test
  <<: *rules-no-tag-no-release

build-image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker image build --platform=linux/amd64 -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE --all-tags
  <<: *rules-no-tag-no-release

release:
  stage: release
  when: manual
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG == null && $CI_COMMIT_TITLE !~ /^chore: release/'
  <<: *git-setup
  script:
    - |
      if [ -z "$GITLAB_TOKEN" ]; then
        echo "ERROR: GITLAB_TOKEN is not set in CI/CD variables"
        exit 1
      fi
    - export GITLAB_TOKEN="${GITLAB_TOKEN}"
    - npx --yes release-it --ci --verbose
