# .gitlab-ci.yml - Pipeline CI/CD complète

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  NODE_VERSION: "20"

stages:
  - .pre
  - validate
  - test
  - build
  - release

# ==========================================
# 📦 Installation des dépendances
# ==========================================
install:
  stage: .pre
  image: node:${NODE_VERSION}-alpine
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  script:
    - npm ci --prefer-offline
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_TAG == null'

# ==========================================
# ✅ VALIDATION
# ==========================================

# Linting
lint:
  stage: validate
  image: node:${NODE_VERSION}-alpine
  dependencies:
    - install
  script:
    - echo "🔍 Running ESLint..."
    - npm run lint
  rules:
    - if: '$CI_COMMIT_TAG == null'

# Formatage
format-check:
  stage: validate
  image: node:${NODE_VERSION}-alpine
  dependencies:
    - install
  script:
    - echo "💅 Checking code formatting..."
    - npm run format:check
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_TAG == null'

# Détection de secrets
secrets-scan:
  stage: validate
  image: zricethezav/gitleaks:latest
  script:
    - echo "🔐 Scanning for secrets..."
    - gitleaks detect --verbose --no-git --redact
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_TAG == null'

# Audit de sécurité npm
security-audit:
  stage: validate
  image: node:${NODE_VERSION}-alpine
  dependencies:
    - install
  script:
    - echo "🛡️ Running npm audit..."
    - npm audit --audit-level=high || true
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_TAG == null'

# Scan de vulnérabilités
vulnerability-scan:
  stage: validate
  image: aquasec/trivy:latest
  script:
    - echo "🔎 Scanning for vulnerabilities..."
    - trivy fs --severity HIGH,CRITICAL --exit-code 0 .
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_TAG == null'

# ==========================================
# 🧪 TESTS
# ==========================================

# Tests unitaires
unit-tests:
  stage: test
  image: node:${NODE_VERSION}-alpine
  dependencies:
    - install
  script:
    - echo "🧪 Running unit tests..."
    - npm run test:unit
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG == null'

# Tests E2E
e2e-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-focal
  dependencies:
    - install
  before_script:
    - npm ci
    - npx playwright install --with-deps chromium
  script:
    - echo "🎭 Running E2E tests..."
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_TAG == null'

# ==========================================
# 🐳 BUILD DOCKER
# ==========================================
build-image:
  stage: build
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🐳 Building Docker image..."
    - |
      docker build \
        --build-arg NODE_VERSION=${NODE_VERSION} \
        -t $DOCKER_IMAGE:$DOCKER_TAG \
        -t $DOCKER_IMAGE:latest \
        .
    
    - echo "📤 Pushing to Container Registry..."
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:latest
    
    - echo "✅ Build complete!"
    - echo "Image: $DOCKER_IMAGE:$DOCKER_TAG"
  rules:
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_BRANCH == "main"'

# ==========================================
# 🚀 RELEASE
# ==========================================
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "🚀 Creating release..."
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: |
      ## 🎉 Release $CI_COMMIT_TAG
      
      ### 📦 Docker Image
      ```
      docker pull  $ DOCKER_IMAGE: $ CI_COMMIT_TAG
      ```
      
      ### 🚀 Run locally
      ```bash
      docker run -p 3000:3000  $ DOCKER_IMAGE: $ CI_COMMIT_TAG
      ```
      
      ### 📋 Changes
      See [CHANGELOG](CHANGELOG.md) for details.
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
